# Prometheus Basic Authentication Configuration
# Reference: https://prometheus.io/docs/guides/basic-auth/

basic_auth_users:
  # Username: admin
  # Password: (See .env GRAFANA_ADMIN_PASSWORD)
  admin: $2b$12$2YzHW5c46NJc4AyzupvGHeclA9mLb0tsvFQXV7ag/uSt1U2Bhnm2u
tls_server_config:
  cert_file: /etc/prometheus/prometheus.crt
  key_file: /etc/prometheus/prometheus.key
